Homework1 task1 ready
VytasR/coherent-homework pull request #1
Opened 2021-12-03 09:37 UTC by VytasR

Task1 - ternary 2's calculator - ready for review

2021-12-06 09:58 UTC, radislavkireev requested changes

2021-12-06 09:58 UTC, radislavkireev commented on Homework1/Ternary2s/Program.cs
> +                if (AreTwoTernary2s(i))
envelope if with {} even when one-liner inside: 

if (AreTwoTernary2s(i)) 
{
   intsWithTwoTernary2s.Add(i, ConvertDecimalToTernary(i));
}

2021-12-06 09:58 UTC, radislavkireev commented on Homework1/Ternary2s/Program.cs
> +                if (AreTwoTernary2s(i))
I do believe that code works, but there is a way to improve it. 

The current app converts decimal to ternary twice - partially at AreTwoTernary2s and in ConvertDecimalToTernary. 
What about convert number to ternary at first and then count 2s in it? 

string ternary = ConvertDecimalToTernary(i) 
foreach(char c in ternary) 
{
   if (c == '2')  //TBD: count "2s" and add to  intsWithTwoTernary2s
}

2021-12-08 07:53 UTC, VytasR commented on Homework1/Ternary2s/Program.cs
> +                if (AreTwoTernary2s(i))
Hello Radislav, I updated the code. Please check. Thanks.

2021-12-09 11:32 UTC, radislavkireev requested changes

2021-12-09 11:32 UTC, radislavkireev commented on Homework1/Ternary2s/Program.cs
> +                    if (c == '2') sum2s++;
add {} even if is one-liner

2021-12-09 11:32 UTC, radislavkireev commented on Homework1/Ternary2s/Program.cs
> +            var ternaryRepresentation = new StringBuilder(5);
why 5?

2021-12-09 11:32 UTC, radislavkireev commented on Homework1/Ternary2s/Program.cs
> +            if (number == 0) return "0";
add {} even if is one liner

2021-12-09 11:32 UTC, radislavkireev commented on Homework1/Ternary2s/Program.cs
> +            if (number < 0) ternaryRepresentation.Insert(0, "-");
add {} even if is one liner

2021-12-09 11:53 UTC, VytasR commented on Homework1/Ternary2s/Program.cs
> +                    if (c == '2') sum2s++;
Added in all instances

2021-12-09 12:19 UTC, VytasR commented on Homework1/Ternary2s/Program.cs
> +            var ternaryRepresentation = new StringBuilder(5);
It covers an integer range from -80 to 242. If more characters need to be added, additional memory for the StringBuilder object will be allocated dynamically, the capacity be doubled. I believe I am saving memory too much here. What would you suggest?

2021-12-14 10:38 UTC, radislavkireev approved these changes

2021-12-14 10:38 UTC, radislavkireev commented on Homework1/Ternary2s/Program.cs
> +            var ternaryRepresentation = new StringBuilder(5);
Use parameterless ctor, so builder can assign more memory when it needs

2021-12-20 13:12 UTC, merged