Homework5 task3 - Vacations - ready
VytasR/coherent-homework pull request #11
Opened 2022-01-31 06:49 UTC by VytasR

Homework5 task3 - Vacations - ready for review

2022-02-06 11:31 UTC, radislavkireev requested changes

2022-02-06 11:31 UTC, radislavkireev commented on Homework5/VacationsApp/CompanyEntities/Company.cs
> +                        if (item != vacationToCompare && !result.Contains((item, vacationToCompare)) &&
You may have possible duplicates in result. 

Consider case when group.vacation contains 2 records with the same First and Last days.
Lets name them v1 and v2. 

After "foreach" result may contain  (v1,v2) and (v2,v1) tuples. They are equal form users perspective, but result.Contains does hot catch it. 

I have not run the code, pls run the tests to check if proposal is valid.

2022-02-07 09:23 UTC, VytasR commented on Homework5/VacationsApp/CompanyEntities/Company.cs
> +                        if (item != vacationToCompare && !result.Contains((item, vacationToCompare)) &&
Thanks for the remark. I have run the tests. If there are 2 Vacation records in the group with the same First and Last days, method returns one (v1, v2) tuple. If there are 3 analogous records, method returns three tuples: (v1, v2), (v1, v3), (v2, v3).

2022-02-09 19:34 UTC, VytasR commented on Homework5/VacationsApp/CompanyEntities/Company.cs
> +                        if (item != vacationToCompare && !result.Contains((item, vacationToCompare)) &&
After today's lecture I wrote the code a bit more elegantly with LINQ. Had to check !result.Contains(v2, v1) before adding to the result. Then no duplicates appear.

2022-02-12 18:04 UTC, radislavkireev requested changes

2022-02-13 10:15 UTC, VytasR commented on Homework5/VacationsApp/CompanyEntities/Company.cs
> +            var result = from month in months
Fixed.

2022-02-16 14:24 UTC, radislavkireev approved these changes

2022-02-16 15:46 UTC, merged