Homework2 task2 - Training Management System - ready
VytasR/coherent-homework pull request #5
Opened 2021-12-27 13:27 UTC by VytasR

Homework2 task2 - Training Management System - ready for review

2022-01-05 17:49 UTC, radislavkireev requested changes

2022-01-05 17:49 UTC, radislavkireev commented on Homework2/TrainingManagement/TrainingEntity/Training.cs
> +            Training other = new Training(new StringBuilder(Description).ToString());
you do not need to envelope strings to StringBuilder any time, that does not bring benefits.
Replace with `
Training other = new Training(Description);`

Apply similar update to the code below in Clone method.

2022-01-05 17:49 UTC, radislavkireev commented on Homework2/TrainingManagement/TrainingEntity/Training.cs
> +                if (lesson is Lecture)
more elegant solution would be to create Clone() method in lesson and override it in Lecture / PracticalLesson. 
```
class Lesson 
{
   public abstract Lesson Clone();
}
class Lecture : Lesson
{
  public override Lesson Clone() {  / .. Do the cloning code here ... / }
}
```

After that, Training.Clone will look like

```
foreach(var lesson in Lessons)
{
  other.Add(lesson.Clone());
}
```

2022-01-06 13:11 UTC, VytasR commented on Homework2/TrainingManagement/TrainingEntity/Training.cs
> +            Training other = new Training(new StringBuilder(Description).ToString());
corrected

2022-01-17 10:35 UTC, radislavkireev commented on Homework2/TrainingManagement/LessonEntities/PracticalLesson.cs
> +        public PracticalLesson(string description, string linkToTaskCondition, string linkToSolution):base(description)
minor - add spaces for readability
`
 public PracticalLesson(string description, string linkToTaskCondition, string linkToSolution) **:** base(description)`

2022-01-17 10:36 UTC, radislavkireev approved these changes

2022-01-18 06:57 UTC, VytasR commented on Homework2/TrainingManagement/LessonEntities/PracticalLesson.cs
> +        public PracticalLesson(string description, string linkToTaskCondition, string linkToSolution):base(description)
added

2022-01-18 06:59 UTC, merged